version: 2
jobs:
  build:
    working_directory: ~/batch
    docker:
      - image: fpco/stack-build:lts-10.3
    steps:
      - checkout
      - restore_cache:
          key: stack-cache
      - run:
          name: stack setup
          command: 'stack setup'
      - run:
          name: stack install dependencies
          command: 'stack build --test --bench --only-dependencies'
      - save_cache:
          key: stack-cache
          paths:
            - ~/.stack
            - ~/batch/.stack-work
      - run:
          name: stack build
          command: 'stack build --fast --pedantic'
      - run:
          name: stack test
          command: 'stack test --fast'
